### ISSUE TITLE
Minor highlighting issues

### ISSUE THREAD

**Issue by paulch42** [jonaskrask/vdm-vscode#10]
Keywords are divided into two groups with different colours. This has one unfortunate side effect. In `compose .... of .... end`, `compose` and `of` are one colour, but `end` is the other colour.

The sequence `in seq` is not handled. `in` is coloured, `seq` is not.

The keyword `renamed` is not coloured.

The keyword `struct` is not coloured.

The keyword `dcl` is not coloured.

The keyword `for` is not coloured.

The keyword `state` is not coloured.

The sequence `be st` is not coloured.

The prefix `is_` is not coloured.

**Comment by jonaskrask** [comment]
The mentioned keywords are highlighted in the next release.

I was thinking, should we simplify the keyword highlighting to just one color for all keywords until we have time to do it thoroughly or is it a good thing that we start to introduce different colored keywords on the go? (@paulch42 and @nickbattle)

**Comment by paulch42** [comment]
Using two colours is different from Overture and has its merits. I'd be happy to leave as is for the moment (the `compose` anomaly notwithstanding) until a more thorough approach is considered. However, I don't have a strong opinion either way.
