### ISSUE TITLE
Cannot interrupt long running evaluations

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#11]
A long running evaluation (a print command) cannot be interrupted using the red-square stop button. This is in contrast to a long running combinatorial test, where the stop button works correctly.

If you click the button twice or more times, the session to the DAP server will be disconnected, but that in itself does not terminate the execution and subsequent attempts to start a debug session will not re-connect. The only way out is to close the entire VSC client and restart (which does kill the LAP/DAP process).

Evaluations should use the same CancellableThread technique that combinatorial test execution does.

Related to #9

**Comment by nickbattle** [comment]
A fix for this is under test. It allows both the initialization of specs and the execution of expressions to be interrupted with the red square "stop". The specs sees a ContextException if this happens, and drops into the debugger, which may allow you to see what is happening to take so long. But note that you cannot (as yet) continue with the evaluation.

**Comment by jonaskrask** [comment]
When you press the "stop" button shouldn't it just exit instead of dropping into the debugger?
But, if you press "pause" drop into the debugger and (eventually) be able to continue?

**Comment by nickbattle** [comment]
Yes, I thought about that. It's a nice idea and I want to see how "pause" functions, but the fix that is currently pushed only does a "hard" interrupt. It's a step forward at least! :-)

**Comment by nickbattle** [comment]
Pausing does now seem to work. I've pushed the changes, as discussed.

**Comment by jonaskrask** [comment]
close?

**Comment by nickbattle** [comment]
Definitely.
