### ISSUE TITLE
False error "type does not match"

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#110]
Error message: Exported type does not match actual type, Exported: seq of (char), Actual: seq of (Upper /* opaque */)(3189)

Happens in the project: 
https://github.com/jonaskrask/vdm-vscode/tree/development/resources/examples/VDMSL/DepartureTMISL
and
https://github.com/jonaskrask/vdm-vscode/tree/development/resources/examples/VDMSL/ISO8601SL

Upper is of type "char" hence the "code" in the spec should be allowed (I think. It is in Overture).

**Comment by jonaskrask** [comment]
Related to #76

**Comment by nickbattle** [comment]
Does it work if the export has "struct" added to it?

**Comment by jonaskrask** [comment]
Where would you put "struct"?

**Comment by nickbattle** [comment]
On the export clause for the type that is giving trouble - it should say `exports types whatever struct` or, if it already has such a struct clause, try removing the struct part :-)  I can never remember whether struct makes them opaque or makes them visible(!)

**Comment by jonaskrask** [comment]
Tried putting struct a bunch of places but not sure I understand.. sorry. 

It looks like this currently
```
exports types Upper
              Lower
              Letter
              Digit
              Octal
              Hex
              AlphaNum
              AlphaNumUpper
              AlphaNumLower
              Space
              WhiteSpace
              Phrase
              PhraseUpper
              PhraseLower
              Text
              TextUpper
              TextLower
        values SP, TB, CR, LF : char 
               WHITE_SPACE, UPPER, LOWER, DIGIT, OCTAL, HEX : set of char
               UPPERS, LOWERS, DIGITS, OCTALS, HEXS: seq of char 
        functions toLower: Upper +> Lower
                  toUpper: Lower +> Upper 
```
What is it you suggest?
