### ISSUE TITLE
dlmodule keyword not handled

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#112]
The "dlmodule" keyword is not handled. Don't know what it is supposed to do...

It is used in the project: https://github.com/jonaskrask/vdm-vscode/tree/development/resources/examples/VDMSL/SAFERSL

In the files `geom.vdmsl` and `gui.vdmsl`

**Comment by nickbattle** [comment]
Yeah that's an ancient VDMTools feature, to allow modules to be provided by DLLs (I think). VDMJ just doesn't support that, so we would have to drop that example.

**Comment by jonaskrask** [comment]
Okay, will do
