### ISSUE TITLE
Scope error in PP/diet2japanPP

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#116]
When running the launch configuration "Launch diet2japanPP Debug 2" i get the following error, but to me this seems like it should be possible?

![image](https://user-images.githubusercontent.com/17763798/154077174-fa100a04-d1d2-410d-b154-24304865b5aa.png)

**Comment by nickbattle** [comment]
Hmmm, yes that does look strange. I'll try to reproduce it.

**Comment by nickbattle** [comment]
This looks like quite a nasty case, caused by a mixture of curried functions and lambda values. The function returned by the application of the first curried parameter (p) does not include "p" in the free variables, by the look of it. I'll investigate further...
