### ISSUE TITLE
Adding ignore folders to VDMSL project

### ISSUE THREAD

**Issue by leouk** [jonaskrask/vdm-vscode#118]
Imagine a setup where a Java Maven project is loaded. 

Then its src/test/resource/*.vdmsl has the tests, where src/test/java/*.java has the jUnit code. 

Then after mvn clean install, we will have duplicate VDMSL files in /src/test/resource/*.vdmsl and /target/test-classes/*.vdmsl will contain the same VDMSL file again, which will lead to a "duplicate module" error. 

It is not possible to load the Java project from within /src/main directly, as this wouldn't contain the Maven POM file and necessary dependencies setup. 

So, how to ignore anything *.VDMSL in /target/test-classes/*.vdmsl?

**Comment by nickbattle** [comment]
Yes, it would be useful to be able to "pick" the folders to include or ignore, like a ".vdmignore" file (by tradition). Currently, the parser will ignore any (sub-*)folder that starts with a ".", like ".generated" etc. But there are systems, like Maven, that create standard (ignorable) folders which cannot easily be renamed like this.

There is a small workaround/hack, which Leo sometimes uses: the "ordering" file (if it exists in .vscode) defines the files to include in the project, and their parsing order. You can use this to "include" rather than "ignore" files, which may help if you're stuck?

**Comment by nickbattle** [comment]
Incidentally, you can produce the "ordering" file using the VDMJ command line plugins jar, which adds a command called "order". Usually the order of your files doesn't make much difference, but for very large projects it can considerably improve the typecheck performance if you have files in dependency-order... though calculating that dependency order is hard (literally NP-hard, I believe, but the algorithm has a best guess!)

**Comment by leouk** [comment]
> Yes, it would be useful to be able to "pick" the folders to include or ignore, like a ".vdmignore" file (by tradition). Currently, the parser will ignore any (sub-*)folder that starts with a ".", like ".generated" etc. But there are systems, like Maven, that create standard (ignorable) folders which cannot easily be renamed like this.
> 
> There is a small workaround/hack, which Leo sometimes uses: the "ordering" file (if it exists in .vscode) defines the files to include in the project, and their parsing order. You can use this to "include" rather than "ignore" files, which may help if you're stuck?

I see. Having some ignore capability would be useful. I thought to add something to Maven itself (like you can ignore certain target dirs say if they have generated java, but given it's the VDM engine, wouldn't work (it's not POM-sensitive). 
Jonas suggested the renaming to .resource, but than maven won't be happy with jUnit testing.  

Yes, had forgotten about order option! Nice one. Let me try.

**Comment by leouk** [comment]
> Incidentally, you can produce the "ordering" file using the VDMJ command line plugins jar, which adds a command called "order". Usually the order of your files doesn't make much difference, but for very large projects it can considerably improve the typecheck performance if you have files in dependency-order... though calculating that dependency order is hard (literally NP-hard, I believe, but the algorithm has a best guess!)

Okay. Generated the "ordering" file with the "order" plugin (in VDM_Toolkit ~/git/VDM_Toolkit/plugins/vdm2isa/java/src/test/resources/ordering), but wasn't sure where to put it. Added to ~/.vscode/extensions/jonaskrask.vdm-vscode-1.3.2/resources/jars/vdmj/ordering  but that didn't work. 

Where to drop it?

**Comment by nickbattle** [comment]
_the "ordering" file (if it exists in .vscode) defines the files to include in the project_

So there should be a .vscode folder in your project that may include launch.json and settings.json. Put it there, called "ordering":
```
private static final String ORDERING = ".vscode/ordering";
```
I think it has "project relative filenames", though the order command should have done that correctly.

**Comment by leouk** [comment]
> _the "ordering" file (if it exists in .vscode) defines the files to include in the project_
> 
> So there should be a .vscode folder in your project that may include launch.json and settings.json. Put it there, called "ordering":
> 
> ```
> private static final String ORDERING = ".vscode/ordering";
> ```
> 
> I think it has "project relative filenames", though the order command should have done that correctly.

Ah! I see. Do you mean running the order plugin within VSCode debug session? Taht won't go given the errors! 

So I run vdmj on cmd line on all files; generated the ordering file on src/test/resources/ordering, then symbolic linked to .vscode (project local) and yes, it worked ;-). Nice one.

**Comment by leouk** [comment]
Yep!

By the way, what’s the ISAPluginPR? Proof generator?

Thought to give access to isapog to the menu.

Best
Léo

On 17 Feb 2022, at 18:54, Nick Battle ***@***.***> wrote:

﻿

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

You can't run VDMJ cmd line plugins from the VSCode console, alas. They're
very different things, even though I tried to make them look the same. You
can't run scripts either, etc. (Yet... !)

(On phone)

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonaskrask%2Fvdm-vscode%2Fissues%2F118%23issuecomment-1043243358&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C0e1d5b521105459f99c408d9f23e9834%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637807172929651432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gKOaf42AGoVFcF2S8X2FQrh7bkFXgoMkQS%2FMqqvQOmI%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAN63QKSVX3IIK2VCDQPYJDU3UY6TANCNFSM5OUCU5PA&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C0e1d5b521105459f99c408d9f23e9834%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637807172929651432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=J4ai4ZnsVSoWvjRtxUuhJegwvPhmnUZ6Nd6g%2BGHtHv0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C0e1d5b521105459f99c408d9f23e9834%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637807172929651432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u8jHLzFe2rS3MjaP8RyUgkVYZYtV3h2rMNFQd3VOKqM%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C0e1d5b521105459f99c408d9f23e9834%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637807172929651432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wF%2BXY2gmbKuQO4feeyaTouq9NeBGnUM1RLhioH2nX5k%3D&reserved=0>.

**Comment by nickbattle** [comment]
The VSCode plugins come in two flavours: SL and PP+RT. ie. modules and
classes. So I called them XYZPluginSL and XYZPluginPR, because I wanted the
names to be the same length! :-)

**Comment by nickbattle** [comment]
I've just pushed something to "development" that uses a file called ".vscode/vdmignore". That can contain specific files, or folders (relative to the project root, so like "ordering"). These files should be ignored.

Can you try it?

**Comment by nickbattle** [comment]
I've pushed a few more fixes for this. But it seems to work OK now - from the original query, try putting `target` in `.vscode/vdmignore`. That should then ignore all the generated files that Maven writes under target.

**Comment by nickbattle** [comment]
@jonaskrask  If this feature proves to be useful, perhaps we could add something to the file/folder context menus to "Ignore this VDM file" (or VDM files in this folder)? Maybe switching to "Include this..." afterwards? The action is just to edit the contents of `.vscode/vdmignore`.

**Comment by jonaskrask** [comment]
I will give it a try.
Adding an "Ignore this file/folder" should be fairly straightforward to add. 
Also, are you sure you want to make this vscode specific? I was thinking that we would look for a `.vdmignore` file and not `.vscode/vdmignore`

**Comment by nickbattle** [comment]
Yes, I thought about it being VSC specific. Not sure. But plain VDMJ
doesn't have this problem because you name sources directly, so it doesn't
really need the ignore feature. So it's a VSC thing only?

**Comment by jonaskrask** [comment]
You can't add a folder of vdm files as sources in VDMJ? I would think that it would be nice to be able to, especially if you want to launch a large spec.

**Comment by nickbattle** [comment]
Yes, you can do that, and it expands to all of the relevant files within (*.vdmpp or whatever, but without recursing). If you wanted to selectively ignore some of them, you'd have to list the ones to include explicitly. Part of the problem is that, without a clear "project" folder to add .vdmignore to, you'd have to look in every folder processed. It's all possible, but I just don't see that it adds much. Whereas for VSCode, it's essential because it has a recursive file scanner.
