### ISSUE TITLE
Remove syntax highlighting outside /begin{vdm_al} ... /end{vdm_al} scopes

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#121]
Currently, the text outside those scopes are also full of syntax highlights, which is really ugly... we should make sure that if there is a latex scope in an extension then there is only highlighting within those scopes.

**Comment by FrederikPM** [comment]
@nickbattle I can not find a way to successfully tokenise lines before the first `\begin` in a file simply by pattern matching with Oniguruma regex and TextMate logic. But, [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) seems usable for tokenising those lines. However, the theme installed by the user would have to have enabled support for semantic highlighting (most seems to do by default). It also seems that semantic highlighting could be used to enable us to highlight constructs like functions, instance variables, types, classes and so on depending on whether the language server knows about these.
However, I'm not sure how much effort we would like to put into this part of syntax highlighting?

**Comment by FrederikPM** [comment]
Hmm. Testing the semantic highlighting it only adds to the existing token(s). So it cannot be used to to tokenise lines before the first `\begin`. This leaves me at a bit of a loss on how we would achieve that.

**Comment by nickbattle** [comment]
I'm surprised. You're saying we cannot recognise the \section, \subsection etc LaTeX keywords that the VDMJ parser uses to ignore everything until a \begin?

**Comment by FrederikPM** [comment]
Ah. Yes of course we can match those keywords, I didn't think about that. I was thinking that the `\begin` and `\end` labels should signal that everything outside such as scope was to be highlighted as LaTeX.

**Comment by FrederikPM** [comment]
I have changed the pattern matching to now also look for the keywords that the VDMJ parser uses. However, the match unfortunately works such that every line including after the match will be tokenised as LaTeX instead of VDM until a `\begin` is found.
Also, I found [this LaTeX grammar](https://github.com/jlelong/vscode-latex-basics), which I have included so that lines tokenised as LaTeX gets syntax highlight. As I understand it we are free to use MIT licensed work as we are under the GPL license?

**Comment by nickbattle** [comment]
OK, but why is that "unfortunate"? Ideally we would want the LaTeX to be subdued somehow, so that the VDM sections stand out clearly, but it doesn't really matter if the LaTeX keywords are enhanced, as long as they are also comparatively subdued. Presumably we can choose the keyword highlight colour on a per-parsed-language basis?

**Comment by FrederikPM** [comment]
Hmm. Maybe its just an edge-case that no one will fall into but if you accidentally (without any intention of writing LaTeX ) start a line in a vdm file with any of the keywords the VDM syntax highlighting will be removed from that line onwards. 
We cannot choose the colour as that is done by the users selected theme according to the token of the given line. So if we want it subdued the best I think we can do is to specify a token for the LaTeX line that most themes does not target with any colour.
Thus, the LaTeX lines will match the default text colour of the theme.

**Comment by nickbattle** [comment]
The use case is that people who wish to write LaTeX source may do so, as long as they start with those keywords. VDMJ is the same. I think Overture was too! So it's fine that, if they do this accidentally, the source is parsed as LaTeX.

I see what you mean about user colours, but I would guess that the majority of our users will just take the packaged extension and use whatever it comes with? So we should make this behaviour as we want it to be, and then if they install other things that change it, that's not our fault :-)

(I'm away for a few days, typing in a hotel room, so will be quiet for the rest of the day).

**Comment by FrederikPM** [comment]
I have found that we can let the extension contribute to the users configuration settings such that every text line with a given token, `meta.embedded.inline.latex` in our case, will have a specific colour and font style. To give LaTeX lines a subdued look that works with the default themes (dark, light, contrast) I have specified the hex colour `#7c7c7c` and _italic_ font style. You can try it out with the latest [action](https://github.com/jonaskrask/vdm-vscode/actions/runs/1998473229) and see if the colour and style is okay.
If you can override the default colour and font style by defining the following in your settings.json: 
`"configurationDefaults": {
            "editor.tokenColorCustomizations": {"textMateRules": [{
                "scope": "meta.embedded.latex",
                "settings": {
                    "fontStyle": "italic",
                    "foreground": "#7c7c7c"
                }
            }]}
        }`

**Comment by nickbattle** [comment]
That looks pretty good! I've only tried a few basic things, but it definitely makes it clear that the LaTeX is somehow in the background.

**Comment by FrederikPM** [comment]
I see. I will go through the examples and see if the matching works as expected :)
