### ISSUE TITLE
vdmj strict flag in VSCode 

### ISSUE THREAD

**Issue by leouk** [jonaskrask/vdm-vscode#126]
Hi Jonas,

Would it be possible to add the vdmj -strict (or even -verbose) flag to VSCode? They are crucial in more complex models, and useful for translation

Leo

**Comment by nickbattle** [comment]
I agree this would make sense, as would other options potentially. We're currently using properties, like -Dlspx.plugins, to pass in settings rather than specific "argv" arguments. We could extend that usage, though it might be better to use a friendlier settings UI if there will be many such options.

**Comment by leouk** [comment]
I exposed all properties of the translator and it was relatively straightforward with a simple
Update to Jason file. But then I see that this might mess the textual ui loop processing options.

L

On 26 Feb 2022, at 16:38, Nick Battle ***@***.***> wrote:

﻿

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

I agree this would make sense, as would other options potentially. We're currently using properties, like -Dlspx.plugins, to pass in settings rather than specific "argv" arguments. We could extend that usage, though it might be better to use a friendlier settings UI if there will be many such options.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonaskrask%2Fvdm-vscode%2Fissues%2F126%23issuecomment-1052215763&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C1d7de202b5b6423fefcb08d9f93e1113%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637814867232556046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=USmt9ZdhHV1UtzafVPT3W4gfoFa2fkBJn%2FpTjsNe3Kg%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAN63QPPYLEFKI57TUNODKDU5DXYBANCNFSM5PMRSS2Q&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C1d7de202b5b6423fefcb08d9f93e1113%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637814867232556046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iegVFZIA9JND0nFtLSOQ3oiHgBx9pUzLZJhmD5TDLXg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C1d7de202b5b6423fefcb08d9f93e1113%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637814867232556046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cbJ5pc7gLsKDkWNfUNcPWWx8HH3J3EFhrb8j2xUiyZ4%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C1d7de202b5b6423fefcb08d9f93e1113%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637814867232556046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OgquBAviEPIRzYzOFj8thbVbJe%2BwkbhbUP9y05Z%2Br6I%3D&reserved=0>.

**Comment by nickbattle** [comment]
On a related matter, we also have to consider which flags can be set in a launch configuration, compared to the global LSP startup. Currently, you can do most of the "set" options in a launch config. So for example, you can launch with "preConditionChecks" set and that will set `Settings.prechecks` accordingly. But `Settings.annotations` is globally set "true" so that the LSP editor works. 

So we have to think about which options are global/Server scope and which are per-launch. The `-strict` flag would be a global, because it affects the parser/tc messages. A `-verbose` option would be... hmm... I think that really is a Diags level, like FINEST? So we could set the `Settings.verbose` switch for VDMJ if the Diag level was very fine. I'm not sure where the verbose output would go though. Probably to the I/O console.

**Comment by leouk** [comment]
Yes, I think strict would be global and -verbose could go to the log?

Jonas an I used the log with “Diag.fine/finest” to see what was happening.

L

On 27 Feb 2022, at 09:56, Nick Battle ***@***.******@***.***>> wrote:

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.


On a related matter, we also have to consider which flags can be set in a launch configuration, compared to the global LSP startup. Currently, you can do most of the "set" options in a launch config. So for example, you can launch with "preConditionChecks" set and that will set Settings.prechecks accordingly. But Settings.annotations is globally set "true" so that the LSP editor works.

So we have to think about which options are global/Server scope and which are per-launch. The -strict flag would be a global, because it affects the parser/tc messages. A -verbose option would be... hmm... I think that really is a Diags level, like FINEST? So we could set the Settings.verbose switch for VDMJ if the Diag level was very fine. I'm not sure where the verbose output would go though. Probably to the I/O console.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonaskrask%2Fvdm-vscode%2Fissues%2F126%23issuecomment-1053444576&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C11dca4a0253745a080f208d9f9d77736%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637815526071562784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h%2B0blEE17Eurhi69bTW8rYSCmXtAoDumgdkNSfChJ7A%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAN63QKMJQZH3GWER3HCZPTU5HYN3ANCNFSM5PMRSS2Q&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C11dca4a0253745a080f208d9f9d77736%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637815526071719002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PxLJh3gpLBZEwhMAi0AvJeTT0SFJ9pgaCIzsLH%2F6PVM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C11dca4a0253745a080f208d9f9d77736%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637815526071719002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n0pHErRvV83r2uiW0O5tfZh9lpzR1s3tqNOFZ80Fjgc%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C11dca4a0253745a080f208d9f9d77736%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637815526071719002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ypRfw23yvjuTba9lIfgrwXym8bIv6XiLxpYmJsNoLKk%3D&reserved=0>.

**Comment by nickbattle** [comment]
Just checked: the `-verbose` option does end up sending information to the VDMJ Console, which is redirected when you have a DAP connection to send LSP "output" messages back to the VSC client. It would then display them in the output window.

**Comment by jonaskrask** [comment]
So if I get you right, you would like a global setting for the -strict flag. Which is a VDMJ flag right? So it should be something like: `vdmj -vdmsl -lsp 8000 -strict`

Since the `-verbose` flag is related to the output and not the log, wouldn't it be better to give it its own setting?

Also, would you like a string entry for adding ad.hoc. settings, like we have for JVMArguments?

**Comment by nickbattle** [comment]
You can pass `-strict` to VDMJ, but all it does is set the `Settings.strict` flag internally. The LSP server doesn't automatically support all of the VDMJ command line options - basically it just has the dialect and the ports, and I think that's worth keeping simple. We can pass anything else we want via -D properties, because it's all hidden from the user anyway.

The way we're going, yes perhaps it would be best to have a nice UI for setting arbitrary properties, even if a few are added via other settings. For example we could have a tickbox for verbose, even if all it does is add a property. Ditto with the file encoding, I think? And the plugins UI adds the property for that etc.

**Comment by jonaskrask** [comment]
Fine with me. No reason to expose a generic interface if it is only a few settings we are talking about. 
@idhugoid we talked about this could be a good first issue for you to get back into the code. Are you interrested?

**Comment by idhugoid** [comment]
Hi Leo,

I added two settings where you can set strict and verbose... You have to checkout hdm/126 for now...

If everyone is happy with the addition, I can merge it into development and close this one.

Cheers,
Hugo

**Comment by leouk** [comment]
Hi Hugo,

Thanks for this.

Best,
Leo

On 10 Mar 2022, at 17:54, idhugoid ***@***.******@***.***>> wrote:

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.


Hi Leo,

I added two settings where you can set strict and verbose... You have to checkout hdm/126 for now...

If everyone is happy with the addition, I can merge it into development and close this one.

Cheers,
Hugo

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonaskrask%2Fvdm-vscode%2Fissues%2F126%23issuecomment-1064337649&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C321036d9b69b4dad0c8508da02bf0fda%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637825316873012265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AxgyrGHv8%2BW3n8TkJVhbC2TEhUhElWElU6mWvPsexxY%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAN63QLIX6AELL74ZUGZ3YDU7IZOJANCNFSM5PMRSS2Q&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C321036d9b69b4dad0c8508da02bf0fda%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637825316873012265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DE1U5hcwhwZDb8YvJYmBIjtTUlSiMr%2Bi1e7cEz0Y3ks%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C321036d9b69b4dad0c8508da02bf0fda%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637825316873012265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=m4LW4X74HcjE%2FPgGnuYyDFpPEKDpeTtDKOPI6KqfNy4%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cleo.freitas%40newcastle.ac.uk%7C321036d9b69b4dad0c8508da02bf0fda%7C9c5012c9b61644c2a91766814fbe3e87%7C1%7C0%7C637825316873012265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V48KKCRzQxAzsem3Oe7j4FpqwtyF29t7LW2eEUBqD8E%3D&reserved=0>.

**Comment by nickbattle** [comment]
I think the VDMJ PR is OK, though I made a comment. I doubt (hope?) you have permission to merge into the development branch directly. Let me know, and I can do it for you.

**Comment by idhugoid** [comment]
Ok. Adapted the VDMJ PR and will merge the vscode edits into development.
