### ISSUE TITLE
PO listing has strange box outlines?

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#139]
The proof obligation panel seems to be using strange characters to(?) try to "box" obligations? But it doesn't quite work - at least not on Linux. There are gaps around the edges and between columns. Perhaps it's neater on Windows (it may be font-dependent). But if this isn't neat everywhere, we should probably keep it simple?

![image](https://user-images.githubusercontent.com/1751423/161043451-1b5584b2-0211-42a5-a56e-12c371894c65.png)

![image](https://user-images.githubusercontent.com/1751423/161043531-50675579-4c53-407a-a958-66472cd46b3c.png)

**Comment by nickbattle** [comment]
One option may be to colour the background of alternate rows differently? Though that might look awful too, depending on the theme. Perhaps a simple "line" between them, rather than a box?

**Comment by FrederikPM** [comment]
The idea with boxing the obligation (or something visually similar) was to enhance the impression of expanding the line.
However, for some reason one of the CSS properties that we use for this caused some visual bugs.
I have fixed it so it now looks like:
![image](https://user-images.githubusercontent.com/17593295/161224397-10c16768-9cc6-4241-af67-1385e0047598.png)

If you think it makes more sense to keep it simple, we could also do that:
![image](https://user-images.githubusercontent.com/17593295/161051194-e7c350e5-68db-4849-a2a1-ae69b57f9094.png)

Yes, I think we would be better off omitting any colouring as although it is possible to fetch common colours that are controlled by the current theme, there does not seem to be one available for alternating table row colours.
