### ISSUE TITLE
Overture feature: support Java code generation

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#19]
Overture allows Java code to be generated from specifications. VDMJ currently does not support this.

**Comment by CThuleHansen** [comment]
And C :)

**Comment by CThuleHansen** [comment]
and Isabelle? Though I do not know the status of this. I started it and helped one of Leo's students getting started.

**Comment by nickbattle** [comment]
Not sure of the status of this now, @idhugoid ?

**Comment by idhugoid** [comment]
We have the Java code generation running and are in the process of adding all the configuration tweaks beyond the currently available default options we hardcode when calling the Overture CG. C-code generation and Isabelle is not currently in the agenda...
