### ISSUE TITLE
Keywords not highlighted

### ISSUE THREAD

**Issue by paulch42** [jonaskrask/vdm-vscode#2]
v1.0.0 installed from Marketplace on MacOS 11.1.

Browsing some VDM-SL specifications in VS Code and comparing with Overture, it was observed the following keywords are not highlighted:

* imports
* exports
* all
* from
* definitions
* nil
* bool
* nat
* nat1
* char
* eq
* ord
* compose
* of
* undefined
* token
* measure
* mk_
* is_
* is not yet specified (only the 'not' is highlighted)

In general `if` is highlighted, but sometimes not. In the following `if` is not highlighted:
```
  Type :: t: nat
  ord t1 < t2 == if t1 <> t2 then undefined else undefined;
```
In the following `if` is highlighted:
```
  Type :: t: nat
  ord t1 < t2 == if t1 = t2 then undefined else undefined;
```
If the operator is `<` then `if` is highlighted, but when it is `>` there is no highlight. The common factor seems to be the presence of `>`.

**Comment by jonaskrask** [comment]
the basic types like nat,nat1 and char should be highlighted but your theme may not show it, if you use one of the default "+" themes it will show e.g. Dark+

**Comment by paulch42** [comment]
I was using Light+. I can see a significant improvement in release 1.0.2.

**Comment by jonaskrask** [comment]
Great, I will mark this issue as closed. Unless something is still missing?
