### ISSUE TITLE
Overture feature: add execution coverage

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#20]
Overture (and VDMJ) record the coverage of a specification - ie. the statements and expressions that have been evaluated since the last "init" call. Overture allows this to be displayed, either in an editor or exported as a PDF file.

**Comment by jonaskrask** [comment]
Update to self:
Support for viewing coverage in VSCode was added in v1.1.3.
Export to PDF is still missing.

**Comment by nickbattle** [comment]
I think Overture's export of coverage was to LaTeX, which can obviously be processed to create PDFs. As far as I know, the option to do this ought still to be available in VDMJ, though it would be done as an option in the "translate" to LaTeX request?

**Comment by jonaskrask** [comment]
Great, if this is available in VDMJ we just need to come up with a format for options for the translate request

**Comment by nickbattle** [comment]
There is definitely a printLatexCoverage option on SourceFile. That produces LaTeX output like the attached, which includes a usage table at the end.
[test.vdm.tex.txt](https://github.com/jonaskrask/vdm-vscode/files/7288958/test.vdm.tex.txt)

**Comment by nickbattle** [comment]
That would work. But isn't the LSP-ish way of doing arbitrary arguments/settings to include an "array of any", as with the arguments in a code-lens response?
```
	/**
	 * Arguments that the command handler should be
	 * invoked with.
	 */
	arguments?: any[];
```

**Comment by jonaskrask** [comment]
Added settings in VSCode for 3 arguments to the translate to latex command, they are: modelOnly, markCoverage, insertCoverageTables.
The two last ones will require a small change to the "fileToLaTeX" function in VDMJ.

The message is now like:
{
    uri?: DocumentUri;
    languageId: string;
    saveUri: DocumentUri;
    arguments?: any[];
}

Example:
{
    uri: "someUri",
    languageId: "latex",
    saveUri: "someUri2",
    arguments: [
        {"modelOnly": true},
        {"markCoverage": false}, 
        {"insertCoverageTables": true}
    ]
}

**Comment by nickbattle** [comment]
There's an attempt at this in the "development" branch. Note that VDMJ had to change too. Can you try this and let me know? (Or build an VSIX file, so I can try it)

**Comment by jonaskrask** [comment]
Hmm.. good question, i think i say something slightly like that somewhere, but there is also others that use a format like "arguments": [ "key=value" ], where all commands accept arguments as string arrays with = used as a separator between key and value. Do you think that is better?

Also, I see that LSP 3.17 will use a type called LSPAny, but that is just something I will need to remember to change :)

**Comment by nickbattle** [comment]
An array suggests they expect positional arguments? The easiest to process would probably be one JSON Object with name/value fields for the arguments. But for now, I've implemented it as you described.

**Comment by jonaskrask** [comment]
I guess the reason for the any[] array is to have something similar to comandline argument such as: 
java --foo true --bar "something".

Yes, one object would probably be the easiest to process. But because of the any[] type we would have to do like:
'arguments': [{key1: value1, key2: value2}]
Would that be preferable?

**Comment by nickbattle** [comment]
It's nicer to have named arguments like that. We're just saying that "the first argument" is a group of settings? I don't feel that strongly about it either way though :)

**Comment by jonaskrask** [comment]
Exactly.

I will have a more thorough check online on Monday, to find if there is a standard way to do it, then I will get back to you. For now lets just leave it as is :)

**Comment by jonaskrask** [comment]
Hmm... It seems that most people use the format where all commands are either flags or use = as a separator between key and value, like: "arguments": [ "key=value", "key2=value2", "--someflag" ]. But in principle we can do as we like, do you have a preference?

**Comment by nickbattle** [comment]
Well, my preference would for arguments itself to be an object "any" rather than an array. Lots of LSP messages do this? If it has to be an array, it's easiest if they're all in one object ("map") within the first argument.

**Comment by jonaskrask** [comment]
The LSP way seems to be that entries with the name "arguments" should be "any[]", whereas if we use the name "options" it is normal to have "any". What do you say we change it to that?

That is:
{
  uri: "someUri",
  languageId: "latex",
  saveUri: "someUri2",
  options: {
    "modelOnly": true,
    "markCoverage": false,
    "insertCoverageTables": true
  }
}

**Comment by nickbattle** [comment]
Perfect. I'll try to get the server tweaked this morning :-)

**Comment by jonaskrask** [comment]
Perfect :)

**Comment by nickbattle** [comment]
That should be available now in the "development" branch. I've passed the options object to all of the other translation cases, even though we don't yet have any use of them - obviously we can add flags as we need to easily in future therefore.

**Comment by jonaskrask** [comment]
Seems like it is not reading the options correctly, can you spot what's not working?

(have pushed the VSIX to branch "issue20")

**Comment by nickbattle** [comment]
Looks OK to me? What were you expecting to see? The request had "modelOnly=true" and the others false, so that would extract just the model between `\begin{vdm_al}` `\end{vdm_al}` marks from a VDM-SL source file that was embedded in LaTeX (which we don't have). But I think the options got through OK.

**Comment by jonaskrask** [comment]
I see what it is now. It is related to the two other options, you have put "else if" instead of "if" :)

**Comment by nickbattle** [comment]
GAH!  OK, tweak pushed :)
