### ISSUE TITLE
Overture feature: add support for a named Remote Control class

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#22]
Overture (and VDMJ) has a feature where a Java class that implements the RemoteControl interface can be named in a launcher. In this case, rather than doing the normal execution processing, VDMJ hands control to the user-written class and allows that to interact with the VDM model.

Typically, people write small Java applets to display some sort of GUI which illustrates the operation of the model. It might be simply a matter of adding such a class name to the launch file schema, and calling the hooks at the VDMJ side, though we would have to make sure LSP and DAP were happy.

**Comment by nickbattle** [comment]
People are starting to ask about this, so I'll have a look at it this week.

**Comment by nickbattle** [comment]
I've added a "remoteControl" option to the VDM launch. If set to a package-qualified Java class name, it will launch a RemoteControl instance after it initializes the specification. This is basically the same as Overture. A few points though:

1. The RemoteControl instance is running within the LSP server, so you can put breakpoints in the VDM and that works fine.
2. But a consequence of (1) is that if you kill your animation, you kill the LSP server. Not sure what to do about this! If the animation exits gracefully, the DAP session will also terminate gracefully - ie. it's like a one-shot evaluation.
3. To get it to work, you have to include your RemoteControl class and any supporting classes on the classpath, naturally. I expected this to work by adding to the "annotationPaths" setting, but this doesn't seem to work? It works fine if I set the classpath via Eclipse in an experimental server.
4. I haven't made the necessary change to include "remoteControl" in the VDM launch schema.

So this is currently available in the "development" branch. Leo is trying to make it work.

**Comment by nickbattle** [comment]
A related point. We are starting to use the annotationPaths setting for several different purposes - obviously annotations, but here for remote control code and I've also used it with people to locate VDMJ properties files, which also use the classpath.

Perhaps it would be better to rename the setting to "classpathAdditions" or something like that?

**Comment by nickbattle** [comment]
I sorted out the problem with the annotationPaths: this has to be a jar or a folder containing jars, it isn't a general purpose classpath addition. So we need to think about whether we keep this as it is and add a separate classpath additions setting, or combine the two. But for now, it works if you put the RemoteControl class in a jar file.

The only real caveat is that the RemoteControl class must terminate gracefully, rather than (say) calling System.exit. In the latter case, the LSP server is terminated. This seems like a reasonable restriction though.

I've merged the changes into master and highprecision, so it's part of the 4.4.4-SNAPSHOT now.

**Comment by nickbattle** [comment]
So a launch.json looks like this, if the Java class is called "Conway" in the "a.b.c" package:
```
		{
			"name": "RemoteControl Test",
			"type": "vdm",
			"request": "launch",
			"noDebug": false,
			"defaultName": null,
			"remoteControl": "a.b.c.Conway"
		}
```
Remember we need the remoteControl field adding to the "vdm" schema? And for the smart launch configuration, we need to make the "command" and "remoteControl" fields mutually exclusive.

**Comment by jonaskrask** [comment]
Nice that you have made this work, I have never tried to use remote control in VDM so will need a short introduction (from Hugo maybe) to be of much help.

Maybe we should make a "classpathAdditions" options and keep the annotationPaths option, will discuss this with @idhugoid .

The termination issue I would like if we can avoid at some later point, but to begin with I think we can live with it.

A mutual exclusion check between "command" and "remoteControl" should be pretty easy to add.

**Comment by nickbattle** [comment]
I think it's a feature of Overture/VDMJ that we never made enough use of. But the idea is that you can "show" a formal model to your stakeholders (domain experts) in such away that they can intuitively explore its behaviour, without being bogged down in the notation or the technicalities of running Overture or VSCode.  Leo was interested in using it to "animate" some of his medical device models to show to experts.

I agree that a classpathAdditions field would probably be best. Then we can give it "usual" classpath semantics, allowing you to add a mixture of jars and folders (annotationPaths seems to expect jars or folders of jars).

It would be nice to separate the animation into a new process for safety. But with Java, that means we would have to re-parse the spec in the child (ie. Java doesn't have a fork, in the UNIX sense).  But as you say, it isn't so bad to start with.
