### ISSUE TITLE
Different log levels

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#24]
Have different log levels on the server + setting for this

**Comment by nickbattle** [comment]
The Client is currently sending `$/setTraceNotification` messages  with the value of "off". They are currently handled by the IgnoreHandler :-)  But the Log class should be enhanced to log at particular levels, presumably driven by this value.

**Comment by jonaskrask** [comment]
Just to be certain that I understand: is the Log class capable of different levels? If so which?

**Comment by nickbattle** [comment]
I have something ready to implement this, but it's not "rolled out" - the Diag class is there, but nothing calls it. I need to understand what the setTraceNotification will pass, in order to translate into the Java Logger levels (off, finest, finer, fine, info, config, warning, severe).

**Comment by nickbattle** [comment]
It looks like the setTrace notification can be "off", "messages" or "verbose", according to the LSP spec. I've mapped "messages" to INFO and "verbose" to "ALL" in Java logging levels. There is also a diag override in the LSPServerDebug case (ie. when you're using experimentalServer) such that you always get all diags.

So the "ALL" startup looks like this:
```
12:18:07.283: [INFO][1] Enabling all logging for debug server
12:18:07.324: [INFO][1] LSP VDM_SL Server listening on port 8000
12:18:07.325: [INFO][12] DAP VDM_SL Server listening on port 8001
12:18:22.404: [FINE][1] >>> LSP {"jsonrpc":"2.0","id":0,"method":"initialize","params":...
12:18:22.423: [INFO][1] Workspace using default encoding
12:18:22.426: [CONFIG][1] Registered analysis plugin: AST
12:18:22.429: [CONFIG][1] Registered analysis plugin: TC
12:18:22.433: [CONFIG][1] Registered analysis plugin: IN
12:18:22.434: [INFO][1] Created LSPWorkspaceManager
12:18:22.450: [INFO][1] Created LSPXWorkspaceManager
12:18:22.451: [FINE][1] Client capability experimental.proofObligationGeneration = true
12:18:22.454: [CONFIG][1] Registered analysis plugin: PO
12:18:22.455: [FINE][1] Client capability experimental.combinatorialTesting = true
12:18:22.457: [CONFIG][1] Registered analysis plugin: CT
12:18:22.459: [SEVERE][1] Plugin class plugins.ISAPluginSL not found
12:18:22.466: [INFO][1] Loading all project files under /home/nick/vscode.tests/TestSL
12:18:22.470: [INFO][1] Loaded file /home/nick/vscode.tests/TestSL/modules.vdmsl
12:18:22.471: [INFO][1] Loaded file /home/nick/vscode.tests/TestSL/test.vdmsl
12:18:22.477: [FINE][1] <<< LSP { "jsonrpc" : "2.0", "result" : { "serverInfo" : { "name" : "VDMJ LSP Server"...
12:18:22.509: [FINE][1] >>> LSP {"jsonrpc":"2.0","method":"initialized","params":{}}
12:18:22.510: [INFO][1] Checking loaded files (initialized)...
12:18:22.516: [FINE][1] Client capability experimental.proofObligationGeneration = true
12:18:22.517: [FINE][1] Client capability experimental.combinatorialTesting = true
12:18:23.535: [INFO][1] Loaded files checked successfully
12:18:23.537: [FINE][1] Client capability experimental.proofObligationGeneration = true
12:18:23.742: [FINE][1] Client capability experimental.combinatorialTesting = true
12:18:23.743: [INFO][1] Checked loaded files.
etc...
```
Each line includes the level and the thread ID (ie. [1] to start with, but note the DAP server is [12] and that spawns many other threads. We'll probably have to go through the exercise of deciding what level various messages are to get sensible quantities.

By default the "real" server logging is OFF. But it can be set, either with the setTrace notification or the -Dlsp.log.level setting.

**Comment by nickbattle** [comment]
It looks like the client isn't passing the `-Dlsp.log.filename` setting any more? I thought it used to. Without this, the Diag class will open a ConsoleHandler, meaning that any diags go to stderr. I think we don't want that under normal circumstances? But the output seems to get to the log folder anyway (below). It is also possible to pass `-Dlsp.log.level` to some level string ("all", "fine", "info" etc), though I don't know when or how that would be set. If this is absent, logging is set to "off".

The only logging that I think we should get by default is one line:
```
08:47:30.763: [ALL][1] Logging level set to OFF
```
That appears in (something like) `logs/20211228T084725/exthost1/output_logging_20211228T084729/2-VDM TestPP.log`

**Comment by nickbattle** [comment]
I noticed that setting the `activateServerLog` setting sends a SetTraceNotification(?) but with the value "off" :) So that produces another line in the log file:
```
08:52:43.783: [ALL][1] Logging level changed from OFF to OFF
```
With that setting, the -Dlsp.log.filename is also passed, though the output appears in the same file as it does by default.

**Comment by nickbattle** [comment]
I've changed Diag, so that if you pass a `-Dlsp.log.filename` the logging level defaults to "INFO". That produces basic logging, as below. But note that when you start debugging, it sends a SetTrace notification which turns logging off (see last line!):
```
09:03:47.546: [ALL][1] Logging level set to INFO
09:03:47.584: [INFO][1] LSP VDM_PP Server connecting to port 34507
09:03:47.594: [INFO][12] DAP VDM_PP Server listening on port 38887
09:03:47.634: [INFO][1] Workspace using default encoding: UTF-8
09:03:47.647: [INFO][1] Created LSPWorkspaceManager
09:03:47.650: [INFO][1] Created LSPXWorkspaceManager
09:03:47.655: [INFO][1] No external plugins configured in lspx.plugins
09:03:47.660: [INFO][1] Loading all project files under /home/nick/vscode.tests/TestPP
09:03:47.663: [INFO][1] Loaded file /home/nick/vscode.tests/TestPP/factorial.vdmpp
09:03:47.664: [INFO][1] Loaded file /home/nick/vscode.tests/TestPP/debugging.vdmpp
09:03:47.665: [INFO][1] Loaded file /home/nick/vscode.tests/TestPP/test.vdmpp
09:03:47.674: [INFO][1] Checking loaded files (initialized)...
09:03:48.380: [INFO][1] Loaded files checked successfully
09:03:48.514: [INFO][1] Checked loaded files.
09:03:48.517: [INFO][1] Opening known file: /home/nick/vscode.tests/TestPP/debugging.vdmpp
09:03:48.536: [INFO][1] Response to id 1 received
09:04:36.855: [INFO][1] Closing file: /home/nick/vscode.tests/TestPP/debugging.vdmpp
09:04:36.871: [INFO][1] Opening known file: /home/nick/vscode.tests/TestPP/factorial.vdmpp
09:05:02.463: [ALL][1] Logging level changed from INFO to OFF
```

**Comment by jonaskrask** [comment]
Took me a while to figure out how this trace setting works...

Apparently, VS Code has a built-in configuration called `<extensionID>.trace.server` that if set to `"message"` or `"verbose"` will create an output console where all messages going between the client and the server are printed:
![image](https://user-images.githubusercontent.com/17763798/148554495-dc620b5a-67bc-4829-816e-ec05f1d4d7f9.png)

Whatever `vdm-vscode.trace.server` is set to is reflected in the `trace` setting during initialization and, if changed, followed up with a `$/setTraceNotification` (this is maybe changed to `$/setTrace` in a later version of the client, will have to check when updating the dependency (#79)...).

If the `trace` configuration is set to "message" or "verbose" the server is allowed to send [LogTrace Notifications](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#logTrace).
As far as I understand these messages will then be displayed in the same output console as the message trace.


Based on this information I think we should keep the `-Dlsp.log.level` setting and the `trace` configuration separate.

Then we can use the combination of `-Dlsp.log.filename` and `-Dlsp.log.level` for detailed logging of the server, (maybe) using the standard Java logging levels.

And (if you like) send LogTrace Notifications for vital errors/warnings.

**Comment by jonaskrask** [comment]
Alternatively, we can completely remove `-Dlsp.log.filename` and `-Dlsp.log.level` and only use trace and LogTrace notifications.
However, I think this will make server debugging a bit harder?

**Comment by nickbattle** [comment]
Hmmm. OK, thanks for explaining what's going on here. That makes more sense now.

I think we have two separate requirements. We really need server diags (that get dumped into the logs somewhere) for our own debugging. I don't really see the need to add log notifications too from the server, though perhaps SEVERE ones could raise a notification too perhaps.

It would be easy to include an alternative RPC handler for $/setTrace in anticipation, if we know that is coming soon?

**Comment by jonaskrask** [comment]
Agree, then I think we should remove the link between the trace configuration and the log level.
Then use the `-Dlsp.log.filename` and `-Dlsp.log.level` for server diags. For that I can easily set up a configuration where you can select between the Java log levels?

I don't think there is any reason to use the log notifications if we do like that.

According to the spec the name of the SetTrace Notification should be `$/setTrace` and not `$/setTraceNotification` so it would be nice to include the alternative RPC handler

**Comment by nickbattle** [comment]
OK, I just pushed a tweak to ignore setTraceNotifications (actually to Diag a warning :-) and added $/setTrace to use the same handler.

**Comment by jonaskrask** [comment]
What options are there for -Dlsp.log.level?

**Comment by jonaskrask** [comment]
Found it :) So now you have the following option instead of the boolean option "development.activateServerLogging"
![image](https://user-images.githubusercontent.com/17763798/148566095-c057df1c-579b-4afb-ab52-6d02cca551f9.png)

**Comment by nickbattle** [comment]
Very nice.

Is it possible to add a link to the folder where the log will be generated?
They can be tedious/hard to find otherwise?

**Comment by jonaskrask** [comment]
Done
