### ISSUE TITLE
Warnings for unused imports

### ISSUE THREAD

**Issue by paulch42** [jonaskrask/vdm-vscode#29]
Items in the import list of a module need not be referenced in the module, in which case they are redundant. While not an error, it would be useful to raise a warning for the redundant imports.

**Comment by nickbattle** [comment]
I'm seeing unused warnings. Do you have a simple example that shows the problem? I'm testing with...
```
module A
exports all
definitions
types
	A = nat;
	B = nat;

functions
	C: nat -> nat
	C(a) == a + 1;

	D: nat -> nat
	D(a) == a + 1;

end A

module B
imports from A types A; B functions C; D renamed DD   <--- Warnings all here

end B

Warning 5000: Definition 'A' not used in 'B' (test.vdm) at line 18:22
Warning 5000: Definition 'B' not used in 'B' (test.vdm) at line 18:25
Warning 5000: Definition 'C' not used in 'B' (test.vdm) at line 18:37
Warning 5000: Definition 'DD' not used in 'B' (test.vdm) at line 18:50

```

**Comment by paulch42** [comment]
In my case I was importing all then not referencing anything in the imported module. I didn't notice there were warnings for individually named imports.
```
module a

exports all

definitions

types

A = nat

end a
```
```
module b

imports from a all

exports all

definitions

types

B = nat

end b
```

**Comment by nickbattle** [comment]
Oh I see, thanks. So we'd have to check whether there were *any* imports that come through the "imports all". That might be possible; I'll take a look.

**Comment by nickbattle** [comment]
OK, I've made a change. Now your example says:
```
Warning 5000: Imports from 'a' are not used in 'b' (test.vdm) at line 15:16
Type checked 2 modules in 0.257 secs. No type errors and 1 warning
```
The location 15:16 corresponds to the word "all" on the imports line.
