### ISSUE TITLE
Auto-insertion of '>'

### ISSUE THREAD

**Issue by paulch42** [jonaskrask/vdm-vscode#3]
When I enter the character `<` in the editor, `>` is automatically added immediately afterwards. Presumably this is the facilitate the entry of quote types. However, when the intent is the 'less than' operator it is then necessary to delete the `>` manually. This could get rather annoying and I would rather enter the `>` to close the quote than have to delete it when a comparison is intended.

**Comment by jonaskrask** [comment]
This is a very valid point, it has been changed now and will be included in the next patch
