### ISSUE TITLE
Overture feature: we need a way to include a standard library file

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#35]
When projects are created in Overture (or afterwards) you can choose to add a standard library source to your project, like `IO.vdmsl` or `MATH.vdmsl`. These are provided by VDMJ, so we just need some UI friendly way to include a file. It would just mean adding the source to the project folder - linking to the library functionality is then handled by VDMJ (ie. the LSP server).

**Comment by jonaskrask** [comment]
Believe this is what @idhugoid already added?

**Comment by idhugoid** [comment]
Yes!
