### ISSUE TITLE
Launch file "command" entry does not match the schema

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#4]
You can include a "command" entry in a launch,json file that runs a single execution and then terminates. This works, but the command entry shows as "Property command is not allowed" in the launch editor. I think there is a schema file somewhere in the extension that defines the fields that are allowed in a launch?
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "vdm",
            "request": "launch",
            "name": "Launch VDM Debug",
            "stopOnEntry": true,
            "noDebug": false,
            "defaultName": null,
            "command" : "print solvep(P, S, score1)"   <-- Property command is not allowed.
        }
    ]
}
```
This is in version 1.0.1.

**Comment by FrederikPM** [comment]
This is fixed and is included in the next version.
