### ISSUE TITLE
Multiple launches are not prevented

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#41]
If you launch an executable session (so the Debug Console shows an interactive session), you can request another launch from the Run panel (though not via F5 - you have to click the green launch button on the Run panel).

VDMJ cannot support multiple running processes within one server, so it should send back a sensible error. The 2nd process seems to be waiting to start, and does not cause problems, but it should be handled cleanly.

**Comment by nickbattle** [comment]
It looks like this is a client-side decision. No messages are sent to the DAP server when the second launch is made.

**Comment by jonaskrask** [comment]
Client will now prevent multiple launches for the same specification and display a warning.
