### ISSUE TITLE
"Execute All Tests" only runs first trace

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#42]
I was expecting the top level "Execute All Tests" for a module to expand and execute all of the traces defined. But in some cases it only runs the first trace even though the module has more than one trace defined.

This is in release 1.1.1. The example I was testing with is attached.

[Sorting.zip](https://github.com/jonaskrask/vdm-vscode/files/6074979/Sorting.zip)

**Comment by jonaskrask** [comment]
From a quick look around the client seems to be set up correctly for the "Execute all tests". However, I tried executing it with the AlarmSL project, where it pretty consistently run the first two traces, but in the third the server says that the "execute" request was canceled at some point (usually within the first 200 tests). This stops the execution of the remaining tests.

**Log**
[AlarmSL_lang_server.log](https://github.com/jonaskrask/vdm-vscode/files/6091089/AlarmSL_lang_server.log)
Line 175: execution of Trace 3 begins
Line 211: Server thinks the execution should be canceled, however no cancel message has been send from the client?

Another curious thing occurs at line 177 og the log. For some reason the spec. is reported to have changed. However, I have not carried out any changes.

Using the "Sorting" project I also experience the sudden cancel, but there is no "spec changed error"

**Comment by jonaskrask** [comment]
Might be connected to the "workspace/didChangeWatchedFiles" notification that is send from the client a few lines before?

**Comment by nickbattle** [comment]
Thanks for looking at this. It seems like it is, indeed, the change watched files (caused by the creation of the DEFAULT.json output for the trace). That causes a typecheck for some reason and that in turn cancels any outstanding CT that is executing. That's probably linked to the apparent "spec changed" problem too.

**Comment by nickbattle** [comment]
It was unconditionally re-checking the specification, even if the watched files update was for a file that it could ignore. That should now be fixed, and a quick test with the Sorting example runs through all of the traces.

**Comment by nickbattle** [comment]
I just pushed a followup fix for this - it was not noticing normal file saves correctly and so it was missing typechecks.
