### ISSUE TITLE
Debug "defaultName" not working

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#47]
In the debug configuration you can choose to set the "defaultName" which should set the default module/class that the debugger opens in.

However, it seems that only the validity of the class assigned in the field is checked but it is not set correctly.
![Untitled](https://user-images.githubusercontent.com/17763798/128739114-d850656c-42a1-4377-8c45-3ab99e0e8f5e.png)

**Comment by nickbattle** [comment]
Good spot :-)   Actually, the execution does set the default correctly - you will see that the current class or module is as expected if you try to print something - but the banner heading of the debugger is printed before the default is set. I'll move the default setting to before the banner header.

**Comment by nickbattle** [comment]
The fix should now be available on the development branch of lsp.

**Comment by jonaskrask** [comment]
Ahh great, thanks
