### ISSUE TITLE
Go-to-definition different functionality depending on activation

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#48]
It seems there is a different between what happens for "go to definition" depending on if you press ctrl+mouse1 or mouse2->"go to definition" (think that is the same as pressing F12)

I have not looked very much into it, it was just something Peter noticed on his computer

**Comment by jonaskrask** [comment]
Hmm, I can't find any difference either.. I will ask Peter later

**Comment by nickbattle** [comment]
There is an "apparent" difference in behaviour for some cases, that might be confusing. For example, if you have a field expression like `record.field`, an F12 on the record part will take you to the definition of that *variable*. But if you F12 on the field part, that will take you to that field's definition in the *types* section.

**Comment by jonaskrask** [comment]
I think what was observed is caused by VSC, the problem occurs when you have highlighted a word and press F12, then it will not understand it. Don't think there is anything we can do about that

**Comment by nickbattle** [comment]
Hmmm... you're right, I'd never noticed. But as you say, it looks like that's VSC. Close this one?

**Comment by jonaskrask** [comment]
Closing, not something we can do anything about
