### ISSUE TITLE
Use CodeLens to implement "Run"-functionality for all functions

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#49]
Using CodeLens we should be able to view a Run and Debug button over all functions and operations, similar to: https://code.visualstudio.com/assets/docs/java/java-debugging/java-codelens.gif

**Comment by nickbattle** [comment]
Hmmm, interesting. I'll have a look, but as long as the end result is a normal DAP launch, it should be possible.

**Comment by jonaskrask** [comment]
Yes, that was the idea. I don't think it will be that big an issue to generate a normal DAP launch when we have the function definition.

**Comment by nickbattle** [comment]
I've added something to create code lenses for operations and functions. But at the moment, the "command" for each of them is just set to "???" - so naturally when you click them, it says "Command not found" :-)  Are there existing commands that I can use, or do we have to create one, or what?

![codelens](https://user-images.githubusercontent.com/1751423/135608437-3ddea35a-c210-4e2e-a3a4-0f4dd88198e1.png)

**Comment by jonaskrask** [comment]
I think we will have to create some new command like "vdm-vscode.launchDebugLens" with data: 

{
  "uri": string,   -- uri of the file that contains the function/operation
  "noDebug": boolean,  -- similar to what is sent to VDMJ when we launch a run configuration
  "defaultName": string | null, -- Only relevant for VDM-SL (I think)
  "command": string, -- command that must be sent to VDMJ, build from the function/operation definition, e.g., "p new Test().Run()"
  "hasArgument": boolean -- (Maybe) this would be used to display a UI window where the user can input the arguments
}

Based on the above it should be easy to create and launch a run configuration

**Comment by nickbattle** [comment]
Yes, agreed, we need a custom command for this.  At the moment, I return a command that just opens the launch.json. That's the best I could find!

The slight issue is how/when to create arguments. For example, a function might be defined as "add: nat * nat -> nat", and I can prepare a command "print add(?, ?)", but I don't know what to put in the ?s.  In Overture, the command is set as "add(nat, nat)" and you are expected to overwrite the nats with your arguments.  So the command has to be interactive. Is that OK?

**Comment by jonaskrask** [comment]
Yes, I think that's the best we can do. I was thinking that if the "hasArguments" is true, we could somehow prompt the user for argument inputs

**Comment by jonaskrask** [comment]
Cool, I like that

**Comment by jonaskrask** [comment]
Based on email, thing to note about the lenses:
•	You only get "launch | debug" on public functions and operations, not private or protected.
•	You don't get lenses for constructors, since you can't execute them (sensibly).
•	Static calls do not require constructors (ie. you can just call "op(123,456)" rather than "new T().op(123,456)" and the constructors field is absent..
•	There is no constructors entry for the default constructor, but if that's all there is, there will be an empty constructors field (unless the fn/op is static - see above).
•	The lenses can be produced by the AST or the TC, but AST lenses cannot reasonably be executed. They're there so that when you start typing, the lenses don't all disappear.
•	AST lenses are never populated with constructors.
