### ISSUE TITLE
Launch "stopOnEntry" does not have any effect

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#5]
This field of launch.json is always populated, and set to "true". But this is not supported by the LSP server.

Part of the problem is that the launch in VDM drops into a REPL loop, so it only really makes sense to stop on entry if the "command" option is also set to run something. Otherwise, we can't really decide where the "entry" is, since the user is free to evaluate any expression they wish.

Unless someone can think of a sensible interpretation of this field, would it be possible to remove it from the schema?

**Comment by FrederikPM** [comment]
It has been removed from the schema and the change is included as part of the next version.
