### ISSUE TITLE
Improve outline view

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#50]
Would be nice if the outline view displayed the relations between class/function/variable in a tree view instead of the now "flat" view, illustration below.

VDM VSCode right now:
![image](https://user-images.githubusercontent.com/17763798/129315433-a48810bc-7d03-43bc-9c73-167cb5270c68.png)

How it is done for TypeScript:
![image](https://user-images.githubusercontent.com/17763798/129315488-f3a9f261-e667-4031-a132-37f24dcd6269.png)

**Comment by nickbattle** [comment]
Yes, definitely agree that would be better, and there is actually code in the LSP Server to try to do this. But whenever I've used it, the client doesn't understand - so I assume there is something about the nesting that I'm not encoding correctly.

Are you able to see the messages for (here) the TypeScript outline as an example? It might then dawn on me what I'm doing wrong. The LSP protocol spec isn't crystal clear :-(

**Comment by jonaskrask** [comment]
Not really sure how they are dong it, but I managed to get a trace of the messages that are passed to and from the typescript server. I have attached a txt of all the messages that were transmitted by opening the file Util.ts: [trace from util.ts open.txt](https://github.com/jonaskrask/vdm-vscode/files/6981416/trace.from.util.ts.open.txt)

Image of the outline for Util.ts
![image](https://user-images.githubusercontent.com/17763798/129337499-33eed651-9bfa-4ee4-83c7-d97c46e1ef97.png)

From comparing, it seems that they use a request called: encodedSemanticClassifications-full (line 46 in trace)
Comparing the result they get, it seems very similar to the documentSymbol response in LSP, where their ChildItems correspond to the Children in documentSymbol response.

Don't know if this helps?

**Comment by nickbattle** [comment]
Hmmm... not sure what they're using in that case. But I've managed to make some progress by re-trying the code that I had. It does now display a basic nested outline, though I suspect I will have to do more work to make sure the "spans" are correct.

![Screenshot_20210813_122517](https://user-images.githubusercontent.com/1751423/129350371-ad4d6b23-9b4a-4606-8084-617bf02eb0b3.png)

**Comment by jonaskrask** [comment]
Great! just this small bit will help a lot I think

**Comment by nickbattle** [comment]
I've just pushed something to the development branch that is much better. There is nesting, such that anything associated with an outer definition is nested within. So you get the inv/ord/etc functions for a type def within the type, and the pre/post for functions within the function etc. The type of each definition is also listed after the name (which make most sense for functions and operations, so perhaps we should restrict it...)

![Screenshot_20210813_203350](https://user-images.githubusercontent.com/1751423/129409983-fcfd5b20-5c15-46bf-abd1-453c1c0e211d.png)

Are you able to do any testing?

**Comment by nickbattle** [comment]
One thing... it doesn't work well with the "Follow cursor" option. I think this is because the line-spans are not quite right for everything. I'll look at it, but it works fine if you turn this off.

**Comment by nickbattle** [comment]
One other thing! If the specification has type checking errors, the outline defaults to being built via the AST rather than the TC tree (since the latter doesn't exist). Currently, this still produces a flat outline. I think I can improve it a little, but the nested structure mainly comes from the type checking information, which is absent when there are TC errors.

**Comment by nickbattle** [comment]
I've just pushed some changes to improve the structure of the AST outline. Since it lacks the type information, it is still not as good as the TC one, but it's better than a blank display(!). You can see the AST outline when you have syntax errors in the spec (not type errors, as I said above, sorry). Note also that you sometimes have to type one more character in order to get the client to refresh the outline; it doesn't do it when you save, curiously - this is noted in another "bug".

**Comment by nickbattle** [comment]
And a few more changes pushed. This time it include "per" and "mutex" definitions in "sync" sections (VDM++) and I've changed the icon for operations/traces to be different to functions (it looks like a spanner, rather than a box).

I've given it some reasonable testing on large models. It's merged into master and highprecision, so you could release this as a snapshot, if you think it is stable - perhaps try some of your own models first?

**Comment by nickbattle** [comment]
And just fixed class "inv" definitions, which weren't appearing; and made type definitions show the RHS of the type in the description, which makes more sense. Pushed to master/hp/dev.

**Comment by jonaskrask** [comment]
Sounds great! This will make the outline a lot easier to understand and navigate, especially for new users. I don't think it is a very big issue that it doesn't work very well with "Follow cursor", but do you have any idea why this is the case? And should we add it as a separate issue to look at, at some later point?

I agree that it would make sense to restrict the showing of type, such that we don't get a bunch of duplicate name-type entries.

In the AST outline it writes a lot of "unresolved", would it make sense to remove the "unresolved" to get a cleaner view? See example:
![image](https://user-images.githubusercontent.com/17763798/129546042-3f5ae068-4859-4d36-986e-857cc2f27025.png)

**Comment by nickbattle** [comment]
I think the problem with "follow cursor" is that the ranges calculated do not cover the body of the definition, just the name of the definition. So if you position the cursor directly within the name, it will understand; but if you position the cursor within the body of the a function (say), there are no ranges in the outline that match, so it just moves the highlight to the start of the module/class. I can try to add something to calculate "complete spans", but it's not trivial :-(

Is it possible to force the follow-cursor off when the Outline is opened? That might help people.

Good idea with the unresolved types. I should be able to clean that up with a simple pattern match.

Leave it with me for a day. I want to tidy up the whole area now that hierarchical outlines seem stable (I'll remove the old flat stuff) and I want to move the SL/PP coding into the corresponding plugins. But then I think it's "releasable", albeit as a snapshot.

**Comment by jonaskrask** [comment]
That's great! I think I will create a separate issue for the calculation of the "complete spans", it is not critical.

Also, I will look into whether it is possible to force follow-cursor off.

**Comment by nickbattle** [comment]
OK, have a look at the changes I just pushed. I think this is miles better than it was, though there might be some small tweaks that we can think of. Internally, it's much neater too.

By all means create a new issue for the "follow cursor". I think the easiest way to do this is to just make all of the space between adjacent definitions "belong" to the first one. That will be a lot faster than a complex deep parse of the tree looking for location information, and it is very close to what users would expect - ie. if I click somewhere between A and B, the outline would say that I am "within A".

**Comment by nickbattle** [comment]
Hmmm... just found some problems with SL specs that use the DEFAULT module. Will investigate...
