### ISSUE TITLE
Add "Follow cursor" support for the Outline

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#51]
Quote by @nickbattle from #50: I think the easiest way to do this is to just make all of the space between adjacent definitions "belong" to the first one. That will be a lot faster than a complex deep parse of the tree looking for location information, and it is very close to what users would expect - ie. if I click somewhere between A and B, the outline would say that I am "within A".

**Comment by nickbattle** [comment]
I have a draft of this working. There are (inevitably) some subtleties, such as when generated functions all have the same location, like an "ord" clause generating ord_T, min_T and max_T. But it's close.

One advantage I hadn't realised is that, when the scopes are correct, the error/warning markers get highlighted on the right symbol name - so (say) you see "doSomething" go red if there are errors in "doSomething".

**Comment by nickbattle** [comment]
You also get accurate breadcrumbs at the top of the editor window, so you can see the complete nesting of your location, and highlight the various sub-ranges by clicking on the names. Still testing...

**Comment by nickbattle** [comment]
I've pushed the draft to "development". There are still a few quirks, but it basically works. As you would expect, the range of the definitions (that are highlighted from the breadcrumb line) covers more than needed, since it is the gap between definitions. But it's close. You should also see that errors and warnings are correctly counted against the symbol ranges in which they occur in the outline view.

I'll look at the quirks. The end of the file is not quite right and type invariants seem confused... if you spot anything else, let me know (ideally with a small example).

**Comment by nickbattle** [comment]
Ugh... there are still serious problems with large specifications (no outline given). So we can't release this yet :-(  I'll investigate.

**Comment by nickbattle** [comment]
It looks like the "renderer1.log" contains the clues:
```
[2021-08-20 08:34:49.245] [renderer1] [error] selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange
```
Though it doesn't give the actual symbol that's causing the problem!!

**Comment by jonaskrask** [comment]
Is the "range" and "selectionRange" the same for the documentSymbols?
Otherwise you could try and check for illegal selectionRange on the server side?

**Comment by nickbattle** [comment]
Yeah, I added a "verify" check on the server side, then it was obvious (multi-file DEFAULT models caused problems). It's fixed now. I've just pushed to "development" if you want to try it - it's really looking very nice :-)

**Comment by jonaskrask** [comment]
Great! I will give it a try

**Comment by jonaskrask** [comment]
One small issue, if you open an empty file "documentSymbol" will return with an error

**Comment by nickbattle** [comment]
Oops! OK, thanks, I should be able to fix that easily.

**Comment by nickbattle** [comment]
Hmmm... just pushed a small fix for that. But it's really strange: the client doesn't seem to send documentSymbols requests when you might expect, so it can take a while for edits to catch up. Do you know why it's like this?

**Comment by nickbattle** [comment]
There are still issues with a minimal:
```
values
    S = 123
```
It only works if you add a third line, for some reason. This is going to need a LOT of testing :-(

**Comment by nickbattle** [comment]
Right, that should now be fixed/pushed. The problem was when the first definition was also at the end of the file.

**Comment by nickbattle** [comment]
There were some outline problems with RT that I've just fixed and pushed to "development", as well as some "goto definition" problems with pseudo-symbols, like CPU and BUS - that affected VDMJ and LSP.

I also finally figured out what "Filter by Type" means... it means if you set the option, and type into the outline window itself, it filters the outline symbols listed by the string that you type. It seems to work :-)

**Comment by jonaskrask** [comment]
Great!
