### ISSUE TITLE
Add VDMUnit functionality to VDMJ stdlib

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#56]
Related to issue #55, the VDMJ stdlib should also be enhanced with VDMUnit functionality for PP and RT to support the same as the Overture stdlib

**Comment by nickbattle** [comment]
OK, I'll take a look at this one too.

**Comment by nickbattle** [comment]
I've ported over the Java supporting classes for this and imported the VDMPP/RT class into stdlib. All I've done so far is fix the compilation errors, so I have no idea whether (or how!) this is supposed to work. It's really ugly :-(

**Comment by jonaskrask** [comment]
I don't really know how this is supposed to work, so @idhugoid will you have a look when you have time?

**Comment by nickbattle** [comment]
Unlike CSV, this beast is really tricky to test. I'm fairly confident that the basic VDM classes and operations will work fine, but some of the native methods were doing some very complicated things in Overture, and although I think I've converted them, these really need testing carefully.

The changes for this, and CSV are all in the "development" branch at the moment.

**Comment by idhugoid** [comment]
Not yet ...

**Comment by jonaskrask** [comment]
Where did we get with this? Is it implemented on VDMJ and just needs testing or?

**Comment by jonaskrask** [comment]
Seems to work now, tests available in: .../vdm_test_files/VDMUnitDebug
