### ISSUE TITLE
Add Graphviz DOT file as a translation

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#57]
The VDMJ cmd-plugins project includes an "order" command which is capable of producing a Graphviz DOT file, which can subsequently be converted into an image of module or class dependencies (example below). This would be very useful to have as a translation option in VSCode.

The dependency calculation and the ordering are features that we should migrate into VSCode anyway, since the ordering of files may become important for large specifications. Currently this has to be done manually, via command line VDMJ.

![VDM_Toolkit_order](https://user-images.githubusercontent.com/1751423/130942583-a101688c-4770-43c4-9af0-e7398a4c7dbe.png)

**Comment by nickbattle** [comment]
I've just pushed a change to the "development" branch that attempts to create a translate handler for a languageId of "dependencies". It takes the same form as the others, though the "file" argument is ignored (since you can only sensibly produce a dependency graph for all your modules or classes). So it creates a single output file called "dependencies.dot" in the saveUri location.

There's a unit test, which works for modules and classes, but... usual caveats about testing apply :-)

**Comment by nickbattle** [comment]
It may be good enough to leave the DOT file in a .generated subfolder. But if we wanted to create an image to display, we could try to detect the "dot" Graphviz executable from the Client and execute this command:
```
dot -Tpng dependencies.dot -o dependencies.png
```
![dependencies](https://user-images.githubusercontent.com/1751423/131263652-309610ff-4a10-4752-b2b6-1fdd9aa046e3.png)

**Comment by jonaskrask** [comment]
Nice! I have enabled it in the VSCode extension on the "dependencies" branch. A few notes related to this:

- Would like the language ID to be "graphviz", agree?
- Is this also relevant for SL specs or should we hide the functionality for SL specs?
- There exists (at least) one graphviz language support extension on the VSCode market place that is able to generate the picture (with real time update), so we don't need to include that.
- Had an issue generating the graph for the PacemakerRT example project:
![image](https://user-images.githubusercontent.com/17763798/131298855-de1b75f7-0328-4cd8-9d9c-f1d0b2a010b7.png)


Image of how it looks when the "dot" extension is also active:
![image](https://user-images.githubusercontent.com/17763798/131299167-d976fd03-14fd-4a4a-b440-854df6889468.png)

**Comment by jonaskrask** [comment]
It might be possible to check if there is a "dot"-handler installed and otherwise prompt the user with a suggestion to install it, will have a look at some later time (@idhugoid perhaps fitting for Tom?)

**Comment by nickbattle** [comment]
Yes, agree "graphviz" is probably a better languageId :-)

I'll take a look at that NPE. They're usually obvious.

Nice idea to use another DOT plugin!

**Comment by nickbattle** [comment]
OK, I've fixed the NPE (some things to do with RT, which I always forget), and I've changed the name of the languageId to "graphviz". The name of the output file is still "dependencies.dot", since that's what the DOT represents. Potentially we can produce other types of graphviz output in future.

Still on "development" branch.

I also tweaked an error down to a warning for RT so that the PacemakerRT model has no TC errors. It's a subtle case, to do with the use of "time" in a permission predicate. I'm not sure of the rules! But rebuild VDMJ too.

**Comment by jonaskrask** [comment]
Great! Good idea to still call it "dependencies.dot".

Returning to a question from earlier: Is this also relevant for SL specs or should we hide the functionality for SL specs?

**Comment by nickbattle** [comment]
Oh yes, it absolutely matters for SL specs - just ask Leo :-)  The dependencies there are a matter of the imports and exports from modules. If you have a "flat" specification, it has no relevance (and we should check that it doesn't fail in some way, though a flat spec is equivalent to a single module called DEFAULT, so it should be ok).

**Comment by nickbattle** [comment]
I've just tried this with the 1.2.1 VSIX, and it seems fine - though currently it just displays the .dot file source. Presumably, if I installed a Graphviz viewer extension it would just display the graphics? Do we recommend one?

**Comment by nickbattle** [comment]
Hmm... actually, there seems to be gaps in the dependency graphs that I wouldn't expect. I'll take a closer look...

**Comment by jonaskrask** [comment]
I was kinda hoping that vscode would suggest you to install a graphviz extension, but it seems that it doesn't.
We don't really have a way to discover if the user has an extension that can handle .dot files. But I believe it is quite easy to create a suggestion for additional extensions when VDM VSCode is installed.
Other than that I think we should write it in the readme too

**Comment by nickbattle** [comment]
I tried installing the first extension in a search for "graphviz", but it didn't seem to do anything? :-(

I just pushed a fix for the gaps in the dependency graph. It only affected PP and RT specs, which I don't test with as thoroughly :)  It's in "development" for now.

**Comment by nickbattle** [comment]
![dependencies](https://user-images.githubusercontent.com/1751423/132210235-293c1269-a581-4823-84df-977e44575f95.png)

**Comment by jonaskrask** [comment]
I have this extension installed: https://marketplace.visualstudio.com/items?itemName=joaompinto.vscode-graphviz

If you have that installed and open the dependencies.dot file you can press Ctrl+Shift+P and type "graphviz: Open ..." which will display the graph. Alternatively press: Ctrl+Shift+V

Sadly they don't have context many integration of the commands, but it is better than nothing :)

**Comment by nickbattle** [comment]
Yeah, I loaded that extension too. I just couldn't figure out how to display graphs! But it does work. If we can find one that associates itself with the *.dot extension, that would be better?

I've now merged the development fix (mentioned above) down into master/highprecision, after a bit more testing.

**Comment by jonaskrask** [comment]
I think that the extension is associated to *.dot, but the problem is that I would normally expect something like the image below to pop up if an extension is not already associated with an extension
![image](https://user-images.githubusercontent.com/17763798/132229782-e848e287-210b-42ac-9fcd-955d2bef0923.png)

I will see if I can make a suggestion pop-up on installing the VDM VSCode extension, I think that's the best we can do right now.

**Comment by jonaskrask** [comment]
The "joaompinto.vscode-graphviz" extension has been added to the extension pack of VDM VSCode, which will make it so that it is installed whenever VDM VSCode is. Will have to check how this looks on the marketplace when we release next time.

**Comment by nickbattle** [comment]
Is that safe in licensing terms? I don't understand the significance of an extension pack, but if we're bundling someone else's software with ours, I'd at least try to get their agreement or approval?

Also, I just picked this extension because it was the top of the list (probably most often downloaded), but there might be better ones out there. Should we do a quick survey before bundling with this one?

**Comment by jonaskrask** [comment]
Hmm you might be right about the licensing terms.. not quite sure how extension packs are licensed. I have removed it again.

Instead I will just write a small comment on it in the README where the feature is explained.

I quickly went over the other grapviz extensions and it seems like the better one, but I will include one other too.
