### ISSUE TITLE
High precision integers cause internal errors

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#58]
If you have a specification that is written for the high precision build, and it uses very long integer literals that are bigger than Long.MAX_VALUE, the server sends back internal errors on the LSP initialise call. These don't get caught by the client(?) and no "problems" are displayed, but the specification will not parse and the outline is limited etc. Very confusing!

The solution is to switch to high precision, but that isn't obvious as no error is displayed.

**Comment by jonaskrask** [comment]
Yes I think so
