### ISSUE TITLE
Breakpoint support in VDMJ should be enhanced

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#62]
Currently, VDMJ breakpoints can stop on a conditional expression, **or** stop on a hit count, **or** "trace" a single expression value without stopping. These three options are mutually exclusive in VDMJ.

In DAP, breakpoints can be conditional on an expression, **and** also be conditional on a hit count **and** can also be given a log message to produce. The three can be combined.

So currently, VDM VSCode tries to interpret the DAP settings, and possibly produces warning messages if you have combined too many options for VDMJ. But ideally, breakpoint support in VDMJ should be enhanced to bring it up to DAP levels.

This enhancement/bug is just to record the situation for now (in version 1.2.1).

**Comment by nickbattle** [comment]
I've tweaked the DAP breakpoint support slightly to allow `{expression}` substitution in breakpoint "Log messages". So you can set a Log Message of "The values of x = {x} and y = {y}", and the values will be substituted. Note, the parsing is very simple, so if you try to include set expressions, it will get confused (like "The values are {{x, y}}") - the VSCode manual doesn't say what to do in this case.

**Comment by nickbattle** [comment]
Related to this, I've added exception breakpoint support to VDMJ command line and the DAP Server:
```
> help
...
catch [<exp>] - create an exception catchpoint
...

> catch
Created catch [1] (all exceptions)
> p op()
Stopped catch [1] (all exceptions)
8:  		exit 123;
MainThread> 

> remove 1
Cleared catch [1] (all exceptions)
> catch 123
Created catch [2] value = 123
> p op()
Stopped catch [2] value = 123
8:  		exit 123;
MainThread> 

> remove 2
Cleared catch [2] value = 123
> catch 9999
Created catch [3] value = 9999
> p op()
= 0
Executed in 0.003 secs. 
> 
```
You can naturally "step" forwards from the exception to see where it is caught and handled etc.

In the VSCode client, a new label appears in the "Breakpoints" panel, called "VDM Exceptions". This can be enabled/disabled, which catches all exceptions (or not), defaulting to disabled. You can also edit the condition to set a particular exception value, as above with 123. But you can only set one value, as far as I can see (whereas VDMJ will allow multiple catchpoints with different values).

This is currently in the 4.4.4-SNAPSHOT development branch.

**Comment by jonaskrask** [comment]
Can this issue be closed?

**Comment by nickbattle** [comment]
It's better than it was.

Let's close this one. We can create another issue in future to cover the remaining aspects, if we need to.
