### ISSUE TITLE
Sorting of Variables in Debug mode

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#68]
A normal way for PGL to have Global values is to have a class GLOBAL that all other classes inherit from.

This looks a bit confusing in the "Variables" tree when debugging. See example:
![image](https://user-images.githubusercontent.com/17763798/144626156-caff2a05-ac11-4b15-b972-b29c86929ddd.png
)
[vdmDebugInherance.zip](https://github.com/jonaskrask/vdm-vscode/files/7650526/vdmDebugInherance.zip)

Can we somehow hide the values in subclasses, or sort the variables in a way such that all the values are located at the bottom or the top of each instance's variables?

**Comment by nickbattle** [comment]
Hmm... I agree that is confusing. I haven't done very much testing with VDM++. Heaven knows why PGL uses it :^)

I'll take a look. It must be possible to exclude the inherited variables (which is what is going on, by the look of it).

**Comment by nickbattle** [comment]
This is tricky. It's easy to eliminate variables that are not delared within the scope of the object being expanded (ie. which are inherited), but then where do we display them? If I do this, they only appear in the "one liner" for the object:

![image](https://user-images.githubusercontent.com/1751423/144643592-8c29ea0c-cfc7-4c27-8006-911db23e3fc2.png)

**Comment by nickbattle** [comment]
I tried setting the "presentationHint" on these variables to "baseClass", but that didn't change anything :-(

**Comment by nickbattle** [comment]
I've changed it so that the globals are at least shown first in each value. That seems less confusing:

![image](https://user-images.githubusercontent.com/1751423/144648768-5ffca42c-6f59-4bbc-b7d7-a7469b4ec5dc.png)

Unfortunately, the display hints don't seem to do anything. Though there might be a value that does change its appearance.

(Change pushed to "development")

**Comment by nickbattle** [comment]
Hmm... OK, how about this. I've created a pseudo-entry called "inherited" for object that include members that they have inherited from elsewhere. Better?

![image](https://user-images.githubusercontent.com/1751423/144660955-bc536c29-b98c-475e-a1c6-0d89c5d700cf.png)

Now available in development.

**Comment by jonaskrask** [comment]
Looks good! Is it possible to lose the "" marks around the value's names? Alternatively I see that in Overture all the Values are collected under "Global Variables" with a prefix pointing to the file it is specified. Not sure which is better though..
![image](https://user-images.githubusercontent.com/17763798/144723876-bd1e1d75-ae20-4ca6-be5e-e216f5da1da4.png)

**Comment by nickbattle** [comment]
OK, tweaked it to display the fully qualified names (which does make more sense):

![image](https://user-images.githubusercontent.com/1751423/144724385-3f2b89ef-e1f8-405e-b661-61a08a090123.png)

**Comment by jonaskrask** [comment]
Great!

**Comment by nickbattle** [comment]
Isn't this one closed now? The above should be in 1.3.0
