### ISSUE TITLE
Change names of server launch settings

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#70]
Considering changing the names or rather the scope of settings related to launching the server, e.g.:
"vdm-vscode.JVMArguments" to "vdm-vscode.server.JVMArguments"

Think that would be an issue?

**Comment by jonaskrask** [comment]
Note to self: If collecting settings related to server launch under same scope, change "didChangeConfiguration" in "extension.ts" to only restart on these settings.

**Comment by nickbattle** [comment]
Seems sensible. When VDMJ got complicated, I ended up having to rename its properties (similar) to vdmj.<area>.<setting>. It makes things considerably easier to understand (and to extend without adding confusion).

**Comment by jonaskrask** [comment]
Good, will do that then
