### ISSUE TITLE
Add stdlib.jar to the resources

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#73]
VDMJ has been updated to require the Java classes supporting stdlib to be external, rather than being built into VDMJ itself. This allows us to maintain arbitrary libraries independently of VDMJ itself, including user provided libraries.

But this means that stdlib has to be included in the extension resources/jars and resources/jars_highPrecision. I've tried adding the jar here by hand, but that doesn't work :-)  But it does work to include the stdlib via the classpathAdditions, so I'm confident the change will work as expected.

Until this is done, library calls that require native Java will stop at the "is not yet specified". There will also be a message on stderr (the Output window) saying that stdlib needs to be added to the classpath.

**Comment by nickbattle** [comment]
Going forward, we need a way to discover the (arbitrary) libraries on the classpath and allow the user to select from all of them when they go to the "Add VDM Library" dialog.  For example, we can include a MANIFEST entry in library jars that describes them, so that they can be discovered on the fly.

For now, it's fine to include the stdlib VDM resources directly in the extension in resources/lib, but that's not an extensible solution.

**Comment by jonaskrask** [comment]
Changed the way we include the jars in the extension. So now all the jars in the resources/jars/vdmj folder is added to the classpath (or rather the folder is added to the classpath)

**Comment by jonaskrask** [comment]
Hm, seems to work fine though to add all jars in a folder using "-cp .../resources/jars/vdmj/*" or should we avoid that?

**Comment by nickbattle** [comment]
It seems that Java does allow a "*" wildcard after a folder name to mean "all of the jar files within". It came in Java 6, apparently. So that's fine, I think. I was worried that it either didn't work, or that it would depend on Java 14 or something very late.

**Comment by nickbattle** [comment]
Looks like the stdlib library wasn't added to vdmj_hp though? :-)
