### ISSUE TITLE
Auto restart server on configuration changes

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#75]
Don't know if this is possible, but would like to restart the server automatically when configurations affecting the server launch is changed such as classpath additions

**Comment by nickbattle** [comment]
It's a good idea, but I seem to get this anyway sometimes - at least for switches to the experimentalServer setting (which I use all the time). But you're right, it doesn't do it for all settings.

**Comment by jonaskrask** [comment]
Right now the client will ask yo if you want to do the server restart (but only when necessary). My intention with this issue is to remove that, and just restart the server automatically (without notifying the user) whenever necessary.

**Comment by nickbattle** [comment]
Mmm... I like the restart notification/offer. It lets me sort things out with the debugger before I restart. The settings editor seems to save as you type(?) so wouldn't it end up restarting a lot?

**Comment by jonaskrask** [comment]
Yes, it would probably restart quite a lot if you change multiple settings.
Should we just keep the offer instead?

**Comment by nickbattle** [comment]
I think that's best, to be honest.
