### ISSUE TITLE
Better file encoding support

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#80]
Currently, the LSP server reads source files using the default file encoding for the system. On my machines that is UTF-8. Subsequently, when edits are sent from the client, they are also (always) UTF-8 encoded and this all works fine.

But if you force a file to be (say) UTF-16 on a machine that defaults to UTF-8, although the Client notices (see the status bar on the right), this isn't communicated to the server. So in 1.3.0 it will attempt to read a UTF-16 file using UTF-8 and fails. If you subsequently work on the file, the file is sent to the server in a didChange message that carries the content in UTF-8 and the server uses this to sync itself, and recovers.

So we almost get away with it and it does "appear" to work, but the log has all sorts of errors.

I've changed the development branch to look for a `-Dlsp.encoding` property and act accordingly. This would be set via JVMArguments in the project settings.

But it would be better if there was a way for the client to tell the server(?). Failing that, we ought to promote the `lsp.encoding` property from JVMArguments to its own setting.

I wonder how the Japanese manage? Though I think if you do everything in the default local encoding, it will all work, so perhaps that explains it?

**Comment by nickbattle** [comment]
Actually, the UTF-8 content is sent via the didOpen message, though didChange is the same. So this works fine with small test examples that have one file, because as soon as you open a file to start the server, the "broken" file content is replaced with text from the Client. But with multi-file specs, this would fail I think (until you manually opened each one!).
 
Passing the encoding fixes it. But it would be nice if the server could tell us rather than having to have a project setting.

**Comment by nickbattle** [comment]
If we can detect the encoding of a file at the Client (ie. find out what the server put in the status line), could that be added as an experimental option in the initialize message?

I suppose that means that all files in a project would have to have the same encoding though. Hmm.

**Comment by jonaskrask** [comment]
When using the `-Dlsp.encoding` property will the server then act as if all files in the project folder has that encoding?

There is a setting in VSCode called files.encoding where you can select the default encoding for the editor. I can pass that to the server if you want?
![image](https://user-images.githubusercontent.com/17763798/147095121-43cdb783-a322-4c16-923d-8d9e0a213e0c.png)

**Comment by nickbattle** [comment]
Yes, if you set the -D property, all files in the project will be read using that encoding. That seems reasonable: having a mixture would be really complicated?

But the editor appears to auto-detect the encoding of files somehow (it's difficult to do, in general).

![image](https://user-images.githubusercontent.com/1751423/147096538-f55d01de-6be6-41ba-825e-b21a1cbbe7a7.png)

This auto-detection works even if you set the Encoding setting.

Perhaps we should really ask someone like Tomo-san how he works with non-local encodings. If everything is in the local default encoding, I think everything just works. But then he would have problems with ASCII specs, for example?

**Comment by nickbattle** [comment]
Actually, if someone in Japan adds the MATH library to their spec, then they must have a mixture of encodings, unless they set their local encoding to UTF8 (which would cover "ASCII" and Japanese).

If I add MATH.vdmsl to a project that has -Dlsp.encoding=UTF16, I get errors in the MATH module!  Without the -D setting, it appears to work, but I know that the server is choking on the file and depending on the didOpen request to refresh the buffer with "Unicode" (ie. the LSP protocol is UTF8).

I really need an auto-detection in the server, but that's not trivial I think. I'll look at it again...

**Comment by jonaskrask** [comment]
Will you then need to detect the encoding per file? If so, I guess the client can't help much?

**Comment by nickbattle** [comment]
That's right. When you open one file, the server has to parse the whole spec from disk, so it has to open each one and work out what its encoding is. If you're on Linux (and maybe Mac) and the default is UTF8 and the files are too, everything is fine, even for Japanese etc. But ... not everyone is on Linux.

It looks like there are format detecting libraries. But I'm concerned about licensing and performance(!). Still investigating.

**Comment by nickbattle** [comment]
Mmm... these detection libraries are complicated (and probably slow) and their licensing is unhelpful.

I'll think some more, but the simplest thing may be for us to "know" the project encoding and write (say) MATH.vdmsl in that encoding when it is added to the project (the source can be assumed to be UTF8 or part of the library meta-data). Then we just tell the server the project encoding and away we go.

If people force a mixture of encodings (eg. copying files into the project), I'm not sure whether the client could detect that?

**Comment by nickbattle** [comment]
I've changed VDMJ command-line so that if you use a library from stdlib, it will read the stdlib jar as UTF8 but automatically write the local file copy in the encoding that you have set for the session (the cmdline `-c` argument).

I think that, in effect, we will have to do the same for VSCode: when the libraries are selected by the user, they are read in a standard fixed encoding (UTF8 makes sense), and then written out in whatever they have set for `files.encoding` (or the platform default). If that same encoding value is passed to the server via -D, or via an experimental section, it will all work as long as the user doesn't force the encoding of any file to be different.

I can't think of an easy way to sort it out at the server without using a 3rd party library :-(

**Comment by jonaskrask** [comment]
We could do that. Currently the library files are just copied, so it would require a small change to that implementation, but I don't think that's an issue. However, it does not fix the issue with encoding mixes (don't know if this is something people do??).

**Comment by nickbattle** [comment]
Yes, it doesn't prevent people from _forcing_ a mixture of encodings. But the obvious case where this might happen (adding a library) is avoided, and we can tell people _all of the files in the project must follow the `files.encoding` or be the default for your platform_.

If we want to support per-file encoding differences within a project, it needs the server to do auto-detection. And I can't see a simple way to do that.

There _might_ be a way to detect that a file open in an editor is not the default encoding, if we can detect and respond to the setting on the status line. Then at least when they open the file, to see why it's giving trouble, we can pop up a warning to say that it is not following the project encoding?

**Comment by jonaskrask** [comment]
I have changed the "Add library" functionality to convert the library encoding into what is set by the `files.encoding` setting.

However, I was not able to find a way to detect the encoding build into vscode. It seems that their auto-detect feature is powered by [jschardet](https://www.npmjs.com/package/jschardet), but I have not checked up on the library.

**Comment by nickbattle** [comment]
OK. If our library addition uses `files.encoding` (or the platform default, if missing) and that encoding is also passed as `-Dlsp.encoding` to the server, we should be OK for most cases. The awkward folk who want to have a mixture of encodings within one project will have trouble, but I think they shouldn't really be surprised(!).

As a "nice to have", if we were able to use jschardet (when?) to detect files which were not the same as the `files.encoding`, that would at least give a warning to the awkward folk :-)

**Comment by jonaskrask** [comment]
I have added a check to the encoding using jschardet.

Another thing, it seems that VDMJ does not support that many encodings, which I guess is fine, but can we change the "message" that is shown?

Currently (from log): 
11:21:08.634: EXCEPTION: UnsupportedCharsetException utf16le
11:21:08.637: <<< LSP { "jsonrpc" : "2.0", "error" : { "code" : -32603, "message" : "utf16le" }, "id" : 0 }

**Comment by nickbattle** [comment]
VDMJ uses the Java encoding names. If you invoke the command line with a `-c` argument of an unknown char encoding, it lists those that it supports. Here's the current list for me:

[charsets.txt](https://github.com/jonaskrask/vdm-vscode/files/7801488/charsets.txt)

**Comment by jonaskrask** [comment]
Why are those names not the same -.-  ...

**Comment by nickbattle** [comment]
Yeah, not sure. Java has names and aliases, but it seems there are even more aliases from different systems :-(  Do you know where the jschardet names come from?

**Comment by jonaskrask** [comment]
Not really sure where jschardet has the names from but it also seems that I cannot convert to that many different types of encoding anyways.
The function I use only allows the following encodings:
'ascii' | 'utf8' | 'utf-8' | 'utf16le' | 'ucs2' | 'ucs-2' | 'base64' | 'base64url' | 'latin1' | 'binary' | 'hex'

**Comment by nickbattle** [comment]
Well, this was only a "nice to have", so that we could warn about a mixture of encodings within one project. If we can't reliably detect the encoding, we'll just have to depend on them using the right `file.encoding` setting?

**Comment by jonaskrask** [comment]
It seems that the detection from jschardet uses a third set of names for the encodings. So I have removed the check again as it is not very reliable. Thus, we must rely on the user using the right `file.encoding' setting.

I have added a log message under server launch if `file.encoding` is not recognized and a check when adding a library that will warn the user in case the file cannot be converted to the selected `file.encoding`.

I can add a super simple check if you like that just checks if the files are UTF-8 encoded, and if not warns the user that they should select their encoding using the `file.encoding` setting?

**Comment by nickbattle** [comment]
I like the last idea, though how often would this appear? We wouldn't want to annoy people, just because they have to use some strange format.

**Comment by jonaskrask** [comment]
We could do it once every time vscode is opened? And add a setting that would remove it completely?

**Comment by nickbattle** [comment]
Yes, ok that makes sense, especially if it's easy to add a "Do not show this again" toggle.

**Comment by jonaskrask** [comment]
That's no problem, will do
