### ISSUE TITLE
PO View not showing status properly

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#85]
The server can report several statuses for POs the client should be able to show these, rather than assume "proven" for all that are not "unproven".

**Comment by nickbattle** [comment]
At the moment, the JSON response has a "proved" field that is boolean. I will change this to "status" that has the string value of the PO status.

**Comment by nickbattle** [comment]
LOL... doing this actually changes the output to be the way we want?

![image](https://user-images.githubusercontent.com/1751423/147150216-86a511dd-3a9e-46fc-8f25-c087b057412a.png)

Changes in "development"

**Comment by jonaskrask** [comment]
Oh yeah, totally forgot that we simply display all information from the messages more or less "raw"

**Comment by jonaskrask** [comment]
Updated the PO View in VS Code to allow filtering of status, instead of "Hide proved proof obligations"
