### ISSUE TITLE
Debugger termination is inconsistent

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#9]
If you are stopped at a breakpoint and you click the red square to terminate the execution session, the client will send a "terminate" DAP command and that causes the VDMJ execution to stop and return to the REPL command loop. Note that this does not terminate the execution session and you can continue to evaluate another expression. But if you click the red square *again* when debugging, the client will send a "disconnect" command and subsequently drop the socket connection. This obviously ends the execution session!

The problem is that VDMJ is expecting to allow the user to perform multiple expression evaluations in (what VS Code regards as) one DAP session. So we regard a stop at a breakpoint to mean "stop debugging but continue working", whereas DAP regards it as "stop everything you're doing".

As it stands it is mildly annoying, but not a real problem. It might be possible to clear the client's memory of the stop having been sent in its debug session state? Alternatively, we could use the stop button to mean terminate everything, which would require another F5 session to be started afterwards.

The DAP behaviour is defined in this post: https://github.com/microsoft/vscode-node-debug/issues/1#issuecomment-405185642

**Comment by nickbattle** [comment]
Or would it be possible to somehow tweak the client to have two stop buttons for VDM sessions: one that is "soft" and sends a terminate and the other which is hard and sends a "disconnect"?

**Comment by jonaskrask** [comment]
As I read the DAP behavior the "terminate" message is not meant as a "stop but feel free to start something new" but rather "stop controlled". 
I think it would be a bad idea to deviate from the behavior that is expected by the DAP specification, as this could cause problems down the road if the server should be used for another IDE. Thus, I think the solution to use is: the stop button mean terminate everything, which would require another F5 session to be started afterwards.

To return to the REPL loop i would rather use the "restart" command as it seems less restricted in how it is allowed to work.
Currently when you press "restart" in VSC a "terminate" message is sent follow by a new initialization. If we register the capability "supportsRestartRequest" a "restart" command is sent instead, this could allow for a "soft restart" where we simply return to the REPL command loop? 

See "Restart Request" in https://microsoft.github.io/debug-adapter-protocol/specification

**Comment by nickbattle** [comment]
I definitely agree that it's a bad idea to deviate from the DAP model. Perhaps the problem here is that I was expecting the "stop" button to do what the VDMJ stop command does, which exits a debug execution but not the whole session.

If you use the F5 "continue" button when the specification hits an exception, then the result is more or less what we want. That is, control returns to the REPL loop, but you are free to continue to evaluate new expressions. If we change the stop button to mean "exit the session" - gracefully to start with and forcefully if you try again - then perhaps we are in line with what DAP expects?

Restart currently seems to send a terminate followed by a disconnect and a re-initialize, as you say.

**Comment by jonaskrask** [comment]
I'm not entirely sure i get what you mean with "continue", I think it is fine that you can keep running evaluations and continue from breakpoints with F5.

>  If we change the stop button to mean "exit the session" - gracefully to start with and forcefully if you try again - then perhaps we are in line with what DAP expects?
I would think so.

What do you think of making restart a "soft restart" where it simply exits the debug execution if one is running and if not perform a restart of the interpreter?

**Comment by nickbattle** [comment]
You usually "continue" when you're at a breakpoint, and you can use the button to do that. But if the execution stops at an *error*, then you can still click the continue button, but of course it just stops (in the sense of dropping out of the debug phase, back to simple LSP mode). That's quite sensible to me. It means that the stop button is really only used for terminating the whole session, and seems consistent with the DAP model.

A soft restart might work, but to me that is more confusing than using continue to get back to an LSP prompt?

**Comment by jonaskrask** [comment]
If the execution stops at an error I think it is okay to click continue to return to drop out of the debug phase.
And yes, then the stop button is only for full termination of the debug session.

Maybe we should not change the restart behavior then..

One other thing, what if you launch a debug sessions with a "command" in the launch configuration? If i have something like "print new Test1().Run()" as the command, I would expect the debug session to terminate when i press continue at an error. But maybe that is just because i am more used to programming languages..

**Comment by nickbattle** [comment]
So for now, we'll say that the advice is to use "continue" to get out of the debugger at an exception. You *can* use the stop button, but it should really be used to terminate the session, as it will when you are not within an execution (or if you use it twice within a session).

**Comment by jonaskrask** [comment]
can we close this?

**Comment by nickbattle** [comment]
I think so - we understand the issue, so it's reasonable. We can re-open if we need to do more work.

**Comment by nickbattle** [comment]
I've tweaked the termination message to say "Debug session terminated (RESTART is advised)", which only appears if they use the stop button to terminate a debug session (while stepping or at an error). It may help slightly.

**Comment by nickbattle** [comment]
I've tweaked the termination message to say "Debug session terminated (RESTART is advised)", which only appears if they use the stop button to terminate a debug session (while stepping or at an error). It may help slightly.
