### ISSUE TITLE
Live share

### ISSUE THREAD

**Issue by FrederikPM** [jonaskrask/vdm-vscode#91]
Visual Studio Code makes it possible to do real-time code collaboration using their Live Share extension.
It effectively streams a hosts workspace, i.e. files found in a given project to a number of "guests". The guests can then interact with these file together with the host in real-time and changes are propagated to the hosts files.
However, as the sharing functionality only supports standard LSP and DAP and only project files are shared, extended functionality like combinatorial testing and proof obligation generation are only available to the host.
[An issue](https://github.com/MicrosoftDocs/live-share/issues/391) has been opened years ago, however not much if anything has happened to support custom/extended LSP messages.
Therefore, only standard LSP and DAP functionality are available when utilising Live Share.

**Comment by jonaskrask** [comment]
Added a reference to the issue in the related wiki page, will close until new information arives
