### ISSUE TITLE
pog/updated reporting 'successful: true' even though specification has errors

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#95]
E.g. take the AlarmSL example and make a syntax error:

![image](https://user-images.githubusercontent.com/17763798/150772300-a8b7989c-fc0d-4f1c-bf15-3814f7af11c7.png)

Even though this error is present the 'slsp/pog/updated' message has the parameter 'successful' set to true. That parameter should be false as POG is not possible for the specification.

**Comment by nickbattle** [comment]
Hmmm, strange. It is hard-coded to return success, whenever it attempts a PO generation. But as you say, it should not really attempt this if the specification has type or syntax errors.  I can change it to either return (what?) "unsuccessful" if there are errors, or I can not attempt to update POs at all, in which case there would be no notification sent.

**Comment by nickbattle** [comment]
Ah, hold on. It's more subtle than that. Let me check what's happening...

**Comment by nickbattle** [comment]
OK, I've just pushed something to development that should fix this. It was because it was seeing that there were no "TC" type errors, but ignoring the fact that there were "AST" syntax errors.

**Comment by jonaskrask** [comment]
Great, thanks!
